/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.notifications.jsonc --include-runtime=false --env-interface=CallNotePushEnv worker-configuration.notifications.d.ts` (hash: 9378cb39fd0498db5016788e4f92356a)
interface __BaseEnv_CallNotePushEnv {
	DB: D1Database;
	PUSH_SEND_ENABLED: "true";
	PUSH_TRANSPORT: "relay";
	RELAY_BASE_URL: "https://callsum-fcm-relay.holylkh.workers.dev";
	RELAY_KEY_ID: "rkey_v1_eFi9FdhRvFbChH3ZDEfCvw";
	NOTIFICATION_SECRET: string;
	RELAY_HMAC_SECRET: string;
	RELAY: Fetcher /* callsum-fcm-relay */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./workers/call-note-push/index");
	}
	interface Env extends __BaseEnv_CallNotePushEnv {}
}
interface CallNotePushEnv extends __BaseEnv_CallNotePushEnv {}
