/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.relay.jsonc --include-runtime=false --env-interface=CallSumRelayEnv worker-configuration.relay.d.ts` (hash: 4a039cae9e6a89e1adcfbc15f5513d5c)
interface __BaseEnv_CallSumRelayEnv {
	DB: D1Database;
	RELAY_SEND_ENABLED: "true";
	FCM_TARGET_PROJECT_ID: "callsum-b93be";
	RELAY_REQUEST_RATE_LIMIT_PER_MINUTE: "90";
	RELAY_MASTER_SECRET: string;
	RELAY_ADMIN_TOKEN: string;
	FCM_SERVICE_ACCOUNT_JSON: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./workers/fcm-relay/index");
	}
	interface Env extends __BaseEnv_CallSumRelayEnv {}
}
interface CallSumRelayEnv extends __BaseEnv_CallSumRelayEnv {}
