/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.notifications.jsonc --include-runtime=false --env-interface=CallNotePushEnv worker-configuration.notifications.d.ts` (hash: 27d2920505e028e7c83dd3c20a5c8678)
interface __BaseEnv_CallNotePushEnv {
	DB: D1Database;
	PUSH_SEND_ENABLED: "false";
	PUSH_TRANSPORT: "relay";
	RELAY_BASE_URL: "https://callsum-fcm-relay.holylkh.workers.dev";
	RELAY_KEY_ID: "rkey_v1_8HteK9a3twEPfEmKPhRZ6A";
	RELAY_HMAC_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./workers/call-note-push/index");
	}
	interface Env extends __BaseEnv_CallNotePushEnv {}
}
interface CallNotePushEnv extends __BaseEnv_CallNotePushEnv {}
