/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.notifications.jsonc --include-runtime=false --env-interface=CallNotePushEnv worker-configuration.notifications.d.ts` (hash: 3bc3af149bbc70d77a97328c0e6a8ae1)
interface __BaseEnv_CallNotePushEnv {
	PHOTOS: R2Bucket;
	DB: D1Database;
	PUSH_SEND_ENABLED: "false";
	PUSH_TRANSPORT: "relay";
	RELAY_BASE_URL: "https://callsum-fcm-relay.holylkh.workers.dev";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./workers/call-note-push/index");
	}
	interface Env extends __BaseEnv_CallNotePushEnv {}
}
interface CallNotePushEnv extends __BaseEnv_CallNotePushEnv {}
